### ISSUE TITLE
Failed to install at log permissions for translation exception

### ISSUE THREAD

**Issue by Lumi-CLE** [ultraleap/OpenXRHandTracking#13]
The installation stops at step "Log Permissions" after a translation exception.

```
Installing:
 - OpenXR Directory:     DONE
 - API Layer DLLs:       DONE
 - Documentation:        DONE
 - Registry keys:        DONE
 - Uninstaller:          DONE
 - DLL Permissions:      DONE
 - Log Permissions:      FAILED: Exception calling "Translate" with "1" argument(s): "Some or all identity references could not be translated."
```

**Comment by rblenkinsopp** [comment]
Hi There, thanks for the report. That's not an error we've seen before. I'd be interested to get some more details about your system. Can you confirm what version of Windows you are running on?

That error should only affect the ability to write logs when running UWP (Windows Store) applications. This shouldn't cause any issues otherwise. Going forward, we are moving to a different installer which I hope won't exhibit this issue.

**Comment by Lumi-CLE** [comment]
Hi, 
I tested the beta 4 install and it works. 
`XR_EXT_hand_tracking` and` XR_APILAYER_ULTRALEAP_hand_tracking` appear well in the "System Status" tab of Microsoft Mixed Reality OpenXR Developer Tools App.
Thanks for following the issue.

**Comment by rblenkinsopp** [comment]
Great :) Glad to hear that this solved the issue.
